# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f74a07102a47cc81ef1387a0d587351137086ea790186890f5d66d53934cfe96060872628ff723ccb7fb350c53f90bd73aa67ad0428c09303f1a1871ce4e90b

test:
  secret_key_base: 4ea518ebe842c19fa21db08dc70fc89e703d0f063088bc6274cdb66895b09e7742d5ab1c6615e91a11f4714fe7ae34cd0cb6fb3e3b04f848c8719daa9f39fd06

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
